dbusmock: Do not register standard session service directories
martinpitt/python-dbusmock pull request #107
Opened 2022-03-07 19:51 UTC by benzea

Otherwise GTK 4 might try to start the A11Y services, which may fail.

Same thing we already do for system services. Without this, I have the issue that GTK 4 tries to start the A11Y services. This works fine in the CI, but I suppose that is because the service is simply missing.

2022-03-08 07:07 UTC, martinpitt requested changes
Thanks! But let's clean this up a bit.

2022-03-08 07:07 UTC, martinpitt commented on dbusmock/testcase.py
> +            (DBusTestCase.session_bus_pid, addr) = cls.start_dbus(conf=c.name)
This whole part is now identical between start_{session,system}_bus(), aside from the comment. So let's factorize this. @benzea , I'm happy to do that if you don't have time.

2022-03-08 17:02 UTC, martinpitt commented
pylint failure:

    dbusmock/testcase.py:40:4: W0238: Unused private member `DBusTestCase.__start_bus(cls, bus_type)` (unused-private-member)

2022-03-08 17:07 UTC, martinpitt commented on dbusmock/testcase.py
> +        cls.addClassCleanup(setattr, DBusTestCase, 'session_bus_pid', None)
Nice! This is Python ≥ 3.8, last time I tried to introduce it it was still not available on all supported OSes. But seems CI is happy with it now (other than pylint).

2022-03-08 18:14 UTC, benzea commented
I just changed it to explicitly use `DBusTestCase.__start_bus`, kind of makes sense that way.

2022-03-08 18:39 UTC, martinpitt approved these changes
Cheers!

2022-03-08 18:39 UTC, merged

2022-03-09 19:13 UTC, benzea commented
Hrm, maybe this may have been a bad idea.

I did have the issue that in the g-c-c tests, GTK4 tried to start the A11Y services and that failed (causing a warning, causing a crash).

But, now my g-s-d tests are failing because dconf is not running. That is easily fixable though (just explicitly launch `/usr/libexec/dconf-service`).

So, not quite sure what is the right thing for now. Maybe we should have our own service directory and copy some common stuff over?

2022-03-15 08:33 UTC, martinpitt commented
@benzea : My gut feeling is that it's right to not auto-launch services for unit tests. It feels like this should happen explicitly, so that tests control what is running and nothing unexpected happens. Creating the test's own service directory and adding a convenience API to install symlinks into it sounds like a good idea, though!