Ensure method calls from templates are logged
martinpitt/python-dbusmock pull request #109
Opened 2022-03-18 01:59 UTC by whot

For interfaces loaded via a template, calls to static methods were never
logged and the MethodCalled signal was never emitted. Fix this by
wrapping the function from the module in what is a "standard" Python
function debug decorator, except that it adds the calls to the log
instead.

This is a bit awkward since the first argument is always self - we need
to pass that on to the function but we don't want to log it.

*Note: not 100% sure that's the right approach but couldn't think of anything else*

2022-03-21 07:29 UTC, martinpitt requested changes
Many thanks @whot! I like this in general. It is a bit hackish indeed, but mockobject.py is already rummaging around in dbus-python's guts a lot anyway.

However, it [breaks the ofono tests](https://github.com/martinpitt/python-dbusmock/runs/5623295144?check_suite_focus=true#step:3:1358):
```
Traceback (most recent call last):
  File "/tmp/source/tests/test_ofono.py", line 34, in setUpClass
    (cls.p_mock, cls.obj_ofono) = cls.spawn_server_template(
  File "/tmp/source/dbusmock/testcase.py", line 250, in spawn_server_template
    obj.AddTemplate(template, parameters,
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 72, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 141, in __call__
    return self._connection.call_blocking(self._named_service,
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Python.ValueError: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/service.py", line 715, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File "/tmp/source/dbusmock/mockobject.py", line 581, in AddTemplate
    module.load(self, parameters)
  File "/tmp/source/dbusmock/templates/ofono.py", line 48, in load
    mock.AddModem(parameters.get('ModemName', 'ril_0'), {})
  File "/tmp/source/dbusmock/mockobject.py", line 133, in wrapper
    self.MethodCalled(fname, log_args)
  File "/usr/lib/python3/dist-packages/dbus/decorators.py", line 325, in emit_signal
    message.append(signature=signature, *args)
ValueError: Unable to guess signature from an empty dict
```

I'll have a look at this.

2022-03-21 07:29 UTC, martinpitt commented on dbusmock/mockobject.py
> +
Let's drop this excess empty line.

2022-03-21 08:28 UTC, martinpitt commented on dbusmock/mockobject.py
> +
Done.

2022-03-21 08:29 UTC, martinpitt commented
I added a second commit which fixes/works around the problem. It is sort of an API break that automatic signature introspection does not work any more now with static methods, but small enough to be acceptable IMHO (there won't be that many custom templates out there with that problem).

2022-03-21 08:40 UTC, martinpitt approved these changes
Thanks!

2022-03-21 08:40 UTC, merged

2022-03-22 02:43 UTC, whot commented
thanks, much appreciated!

2022-04-02 16:46 UTC, heftig commented
This seems to be pretty broken, see #118.